import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { supabase, supabaseConfigured } from './lib/supabaseClient'
import './App.css'

type Place = { id?: string; name: string; category: string; city: string; wifi: boolean; outlets: boolean; seating: boolean; food: boolean; lat: number; lng: number; created_by?: string }
type Profile = { id: string; display_name: string | null; is_admin: boolean }
const examples: Place[] = [{ name: 'Kraftwerk Berlin', category: 'Café', city: 'Kreuzberg, Berlin', wifi: true, outlets: true, seating: true, food: true, lat: 52.5027, lng: 13.414 }, { name: 'Hotel am Park', category: 'Hotel Lobby', city: 'Tiergarten, Berlin', wifi: true, outlets: true, seating: true, food: false, lat: 52.509, lng: 13.345 }]

function MapView({ places, select }: { places: Place[]; select: (place: Place) => void }) {
  const node = useRef<HTMLDivElement>(null); const map = useRef<L.Map | null>(null); const [position, setPosition] = useState<[number, number]>([52.52, 13.405])
  useEffect(() => { navigator.geolocation?.getCurrentPosition(({ coords }) => setPosition([coords.latitude, coords.longitude]), () => undefined) }, [])
  useEffect(() => { if (!node.current || map.current) return; const instance = L.map(node.current).setView(position, 12); L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', { attribution: '&copy; OpenStreetMap &copy; CARTO' }).addTo(instance); map.current = instance; return () => { instance.remove(); map.current = null } }, [position])
  useEffect(() => { if (!map.current) return; const user = L.circleMarker(position, { radius: 8, color: '#17191b', weight: 3, fillColor: '#d6ff4b', fillOpacity: 1 }).addTo(map.current); const markers = places.map((place) => L.circleMarker([place.lat, place.lng], { radius: 9, color: '#17191b', weight: 3, fillColor: '#ff916c', fillOpacity: 1 }).addTo(map.current!).bindTooltip(place.name).on('click', () => select(place))); return () => { user.remove(); markers.forEach((marker) => marker.remove()) } }, [places, position, select])
  return <div className="map-wrap"><div className="map-node" ref={node} /><div className="map-legend"><span className="legend-dot user-dot" /> Dein Standort <span className="legend-dot place-dot" /> Places</div></div>
}

function App() {
  const [places, setPlaces] = useState(examples); const [selected, setSelected] = useState<Place | null>(examples[0]); const [view, setView] = useState<'map' | 'list'>('map'); const [query, setQuery] = useState(''); const [email, setEmail] = useState<string | null>(null); const [admin, setAdmin] = useState(false); const [profiles, setProfiles] = useState<Profile[]>([]); const [modal, setModal] = useState<'auth' | 'report' | 'admin' | null>(null); const [authMode, setAuthMode] = useState<'login' | 'signup'>('login'); const [message, setMessage] = useState(''); const [title, setTitle] = useState('Finde deinen free2be Place.')
  useEffect(() => { const client = supabase; if (!client) return; const load = async (id?: string) => { if (!id) { setAdmin(false); setProfiles([]); return }; const profile = (await client.from('profiles').select('is_admin').eq('id', id).maybeSingle()).data; const isAdmin = Boolean(profile?.is_admin); setAdmin(isAdmin); if (isAdmin) setProfiles(((await client.from('profiles').select('id, display_name, is_admin').order('created_at', { ascending: false })).data ?? []) as Profile[]) }; client.auth.getSession().then(({ data }) => { setEmail(data.session?.user.email ?? null); void load(data.session?.user.id) }); const listener = client.auth.onAuthStateChange((_event, session) => { setEmail(session?.user.email ?? null); void load(session?.user.id) }); client.from('places').select('*').order('created_at', { ascending: false }).then(({ data }) => { if (data?.length) setPlaces(data as Place[]) }); client.from('site_settings').select('value').eq('key', 'hero_title').maybeSingle().then(({ data }) => { if (data?.value) setTitle(data.value) }); return () => listener.data.subscription.unsubscribe() }, [])
  const visible = places.filter((place) => `${place.name} ${place.category} ${place.city}`.toLowerCase().includes(query.toLowerCase()))
  async function authSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase) { setMessage('Supabase ist nicht konfiguriert.'); return }; const data = new FormData(event.currentTarget); const result = authMode === 'login' ? await supabase.auth.signInWithPassword({ email: String(data.get('email')), password: String(data.get('password')) }) : await supabase.auth.signUp({ email: String(data.get('email')), password: String(data.get('password')) }); setMessage(result.error?.message ?? 'Erfolgreich.'); if (!result.error && authMode === 'login') setModal(null) }
  async function reportSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !email) return; const data = new FormData(event.currentTarget); const user = await supabase.auth.getUser(); const payload = { name: String(data.get('name')), category: String(data.get('category')), city: String(data.get('city')), wifi: data.get('wifi') === 'on', outlets: data.get('outlets') === 'on', seating: data.get('seating') === 'on', food: data.get('food') === 'on', lat: Number(data.get('lat')), lng: Number(data.get('lng')), created_by: user.data.user?.id }; const { data: saved } = await supabase.from('places').insert(payload).select().single(); if (saved) { setPlaces((current) => [saved as Place, ...current]); setSelected(saved as Place) }; setModal(null) }
  async function toggleAdmin(profile: Profile) { if (!supabase || !admin) return; await supabase.from('profiles').update({ is_admin: !profile.is_admin }).eq('id', profile.id); setProfiles((current) => current.map((item) => item.id === profile.id ? { ...item, is_admin: !profile.is_admin } : item)) }
  async function savePlace(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !admin || !selected?.id) return; const data = new FormData(event.currentTarget); const changes = { name: String(data.get('name')), city: String(data.get('city')), category: String(data.get('category')), lat: Number(data.get('lat')), lng: Number(data.get('lng')), wifi: data.get('wifi') === 'on', outlets: data.get('outlets') === 'on', seating: data.get('seating') === 'on', food: data.get('food') === 'on' }; const { data: saved } = await supabase.from('places').update(changes).eq('id', selected.id).select().single(); if (saved) { setPlaces((current) => current.map((place) => place.id === selected.id ? saved as Place : place)); setSelected(saved as Place) } }
  async function deletePlace(id: string) { if (!supabase || !admin) return; await supabase.from('places').delete().eq('id', id); setPlaces((current) => current.filter((place) => place.id !== id)) }
  async function saveTitle(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !admin) return; const value = String(new FormData(event.currentTarget).get('title')); await supabase.from('site_settings').upsert({ key: 'hero_title', value, updated_by: (await supabase.auth.getUser()).data.user?.id }); setTitle(value) }

  return <main className="app-shell"><header className="topbar"><a className="brand" href="#top"><img src="/free2be-logo.svg" alt="free2be" /></a><nav><a className="active" href="#places">Places entdecken</a><a href="#about">Über free2be</a></nav><div className="account-actions">{admin && <button className="quiet-button" type="button" onClick={() => setModal('admin')}>Admin</button>}{email ? <button className="quiet-button" type="button" onClick={() => supabase?.auth.signOut()}>Abmelden</button> : <button className="quiet-button" type="button" onClick={() => setModal('auth')}>Einloggen</button>}<button className="lime-button" type="button" onClick={() => email ? setModal('report') : setModal('auth')}>+ Place melden</button></div></header><section className="welcome" id="top"><div><p className="eyebrow">FREIE ORTE · FREIE VERBINDUNG</p><h1>{title}</h1></div><p className="welcome-copy">Orte, an denen du einfach sein,<br />arbeiten und bleiben kannst.</p></section><section className="places-section" id="places"><div className="section-top"><div className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Suche nach Ort, Stadt oder Kategorie ..." /></div><div className="view-switch"><button className={view === 'map' ? 'selected' : ''} type="button" onClick={() => setView('map')}>◉ Karte</button><button className={view === 'list' ? 'selected' : ''} type="button" onClick={() => setView('list')}>☷ Liste</button></div></div><div className={view === 'map' ? 'places-layout' : 'places-layout list-only'}><div className="place-list"><div className="list-heading"><p className="eyebrow">IN DEINER NÄHE</p><strong>{visible.length} Places gefunden</strong></div>{visible.map((place) => <button className={selected?.name === place.name ? 'place-card selected' : 'place-card'} key={place.id ?? place.name} type="button" onClick={() => setSelected(place)}><span className="place-icon">{place.category === 'Café' ? '☕' : '⌂'}</span><span><strong>{place.name}</strong><small>{place.category} · {place.city}</small><i>{[place.wifi && 'WLAN', place.outlets && 'Steckdose', place.seating && 'Sitzplätze'].filter(Boolean).join(' · ')}</i></span><b>›</b></button>)}</div>{view === 'map' && <MapView places={visible} select={setSelected} />}</div></section><section className="bottom-note" id="about"><span className="lime-mark">✦</span><div><p className="eyebrow">EIN ORT VON MENSCHEN FÜR MENSCHEN</p><h2>Du darfst Raum<br /><em>einnehmen.</em></h2></div><p>Du kennst einen Ort, an dem sich andere<br />willkommen fühlen? Teile ihn.</p><button className="outline-button" type="button" onClick={() => email ? setModal('report') : setModal('auth')}>Place melden ↗</button></section>
    {modal === 'auth' && <div className="modal-backdrop" onClick={() => setModal(null)}><form className="modal-card" onSubmit={authSubmit} onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setModal(null)}>×</button><div className="mode-tabs"><button className={authMode === 'login' ? 'selected' : ''} type="button" onClick={() => setAuthMode('login')}>Einloggen</button><button className={authMode === 'signup' ? 'selected' : ''} type="button" onClick={() => setAuthMode('signup')}>Registrieren</button></div><h2>{authMode === 'login' ? 'Willkommen zurück.' : 'Account erstellen.'}</h2><p className="modal-copy">{supabaseConfigured ? 'Sicher mit free2be verbinden.' : 'Backend noch nicht verbunden.'}</p><label>E-Mail<input name="email" required type="email" /></label><label>Passwort<input name="password" required minLength={8} type="password" /></label>{message && <p className="form-message">{message}</p>}<button className="lime-button submit-button" type="submit">{authMode === 'login' ? 'Einloggen' : 'Registrieren'} <span>↗</span></button></form></div>}
    {modal === 'report' && <div className="modal-backdrop" onClick={() => setModal(null)}><form className="modal-card" onSubmit={reportSubmit} onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setModal(null)}>×</button><p className="eyebrow">FÜR DIE COMMUNITY</p><h2>Place melden.</h2><label>Name<input name="name" required /></label><label>Stadt / Adresse<input name="city" required /></label><div className="form-grid"><input name="lat" type="number" step="any" defaultValue="52.52" required /><input name="lng" type="number" step="any" defaultValue="13.405" required /></div><select name="category"><option>Café</option><option>Hotel Lobby</option><option>Bibliothek</option><option>Sonstiger Ort</option></select><div className="checks"><label><input name="wifi" type="checkbox" defaultChecked /> WLAN</label><label><input name="outlets" type="checkbox" defaultChecked /> Steckdosen</label><label><input name="seating" type="checkbox" defaultChecked /> Sitzplätze</label><label><input name="food" type="checkbox" /> Café / Bistro</label></div><button className="lime-button submit-button" type="submit">Place einreichen <span>↗</span></button></form></div>}
    {modal === 'admin' && <div className="modal-backdrop" onClick={() => setModal(null)}><div className="modal-card admin-card" onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setModal(null)}>×</button><p className="eyebrow">ADMIN BEREICH</p><h2>free2be verwalten.</h2><form onSubmit={saveTitle}><label>Hero-Titel<input name="title" defaultValue={title} /></label><button className="lime-button submit-button" type="submit">Website speichern <span>↗</span></button></form><p className="field-label">Registrierte Nutzer</p><div className="admin-places">{profiles.map((profile) => <div key={profile.id}><span>{profile.display_name || 'Ohne Namen'}<small>{profile.id.slice(0, 8)}</small></span><button type="button" onClick={() => void toggleAdmin(profile)}>{profile.is_admin ? 'Admin entziehen' : 'Zum Admin machen'}</button></div>)}</div><p className="field-label">Places bearbeiten</p><div className="admin-places">{places.filter((place) => place.id).map((place) => <div key={place.id}><span>{place.name}<small>{place.city}</small></span><button type="button" onClick={() => setSelected(place)}>Bearbeiten</button><button type="button" onClick={() => void deletePlace(place.id!)}>Löschen</button></div>)}</div>{selected?.id && <form className="admin-edit-form" onSubmit={savePlace}><input name="name" defaultValue={selected.name} required /><input name="city" defaultValue={selected.city} required /><div className="form-grid"><input name="lat" type="number" step="any" defaultValue={selected.lat} required /><input name="lng" type="number" step="any" defaultValue={selected.lng} required /></div><select name="category" defaultValue={selected.category}><option>Café</option><option>Hotel Lobby</option><option>Bibliothek</option><option>Sonstiger Ort</option></select><div className="checks"><label><input name="wifi" type="checkbox" defaultChecked={selected.wifi} /> WLAN</label><label><input name="outlets" type="checkbox" defaultChecked={selected.outlets} /> Steckdosen</label><label><input name="seating" type="checkbox" defaultChecked={selected.seating} /> Sitzplätze</label><label><input name="food" type="checkbox" defaultChecked={selected.food} /> Café / Bistro</label></div><button className="lime-button submit-button" type="submit">Place speichern <span>↗</span></button></form>}</div></div>}
  </main>
}

export default App
