import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { supabase, supabaseConfigured } from './lib/supabaseClient'
import './App.css'

type Place = { id?: string; name: string; category: string; city: string; wifi: boolean; outlets: boolean; seating: boolean; food: boolean; lat: number; lng: number; created_by?: string }
type AuthMode = 'login' | 'signup'
const examples: Place[] = [
  { name: 'Kraftwerk Berlin', category: 'Café', city: 'Kreuzberg, Berlin', wifi: true, outlets: true, seating: true, food: true, lat: 52.5027, lng: 13.414 },
  { name: 'Hotel am Park', category: 'Hotel Lobby', city: 'Tiergarten, Berlin', wifi: true, outlets: true, seating: true, food: false, lat: 52.509, lng: 13.345 },
  { name: 'Bibliothek am Luisenbad', category: 'Bibliothek', city: 'Wedding, Berlin', wifi: true, outlets: true, seating: true, food: false, lat: 52.551, lng: 13.383 },
]

function PlacesMap({ places, onSelect }: { places: Place[]; onSelect: (place: Place) => void }) {
  const node = useRef<HTMLDivElement>(null)
  const map = useRef<L.Map | null>(null)
  const [position, setPosition] = useState<[number, number]>([52.52, 13.405])
  useEffect(() => { navigator.geolocation?.getCurrentPosition(({ coords }) => setPosition([coords.latitude, coords.longitude]), () => undefined, { enableHighAccuracy: true, timeout: 7000 }) }, [])
  useEffect(() => { if (!node.current || map.current) return; const instance = L.map(node.current, { zoomControl: false }).setView(position, 12); L.control.zoom({ position: 'bottomright' }).addTo(instance); L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', { attribution: '&copy; OpenStreetMap &copy; CARTO' }).addTo(instance); map.current = instance; return () => { instance.remove(); map.current = null } }, [position])
  useEffect(() => { if (!map.current) return; map.current.setView(position, 12); const user = L.circleMarker(position, { radius: 8, color: '#17191b', weight: 3, fillColor: '#d6ff4b', fillOpacity: 1 }).addTo(map.current).bindTooltip('Dein Standort'); const markers = places.map((place) => L.circleMarker([place.lat, place.lng], { radius: 9, color: '#17191b', weight: 3, fillColor: '#ff916c', fillOpacity: 1 }).addTo(map.current!).bindTooltip(place.name).on('click', () => onSelect(place))); return () => { user.remove(); markers.forEach((marker) => marker.remove()) } }, [onSelect, places, position])
  return <div className="map-wrap"><div className="map-node" ref={node} /><div className="map-legend"><span className="legend-dot user-dot" /> Dein Standort <span className="legend-dot place-dot" /> Places</div></div>
}

function App() {
  const [places, setPlaces] = useState(examples); const [selected, setSelected] = useState<Place | null>(examples[0]); const [view, setView] = useState<'map' | 'list'>('map'); const [query, setQuery] = useState(''); const [showAuth, setShowAuth] = useState(false); const [showReport, setShowReport] = useState(false); const [showAdmin, setShowAdmin] = useState(false); const [authMode, setAuthMode] = useState<AuthMode>('login'); const [email, setEmail] = useState<string | null>(null); const [admin, setAdmin] = useState(false); const [message, setMessage] = useState(''); const [title, setTitle] = useState('Finde deinen free2be Place.')
  useEffect(() => { const client = supabase; if (!client) return; client.auth.getSession().then(async ({ data }) => { setEmail(data.session?.user.email ?? null); if (data.session) setAdmin(Boolean((await client.from('profiles').select('is_admin').eq('id', data.session.user.id).single()).data?.is_admin)) }); const listener = client.auth.onAuthStateChange((_event, session) => setEmail(session?.user.email ?? null)); client.from('places').select('*').order('created_at', { ascending: false }).then(({ data }) => { if (data?.length) setPlaces(data as Place[]) }); client.from('site_settings').select('value').eq('key', 'hero_title').single().then(({ data }) => { if (data?.value) setTitle(data.value) }); return () => listener.data.subscription.unsubscribe() }, [])
  const visible = places.filter((place) => `${place.name} ${place.category} ${place.city}`.toLowerCase().includes(query.toLowerCase()))
  const openReport = () => email ? setShowReport(true) : (setAuthMode('login'), setShowAuth(true))
  async function authSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase) { setMessage('Supabase ist noch nicht konfiguriert.'); return }; const data = new FormData(event.currentTarget); const result = authMode === 'login' ? await supabase.auth.signInWithPassword({ email: String(data.get('email')), password: String(data.get('password')) }) : await supabase.auth.signUp({ email: String(data.get('email')), password: String(data.get('password')) }); setMessage(result.error?.message ?? 'Erfolgreich.'); if (!result.error && authMode === 'login') setTimeout(() => setShowAuth(false), 500) }
  async function reportSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !email) return; const data = new FormData(event.currentTarget); const user = await supabase.auth.getUser(); const payload = { name: String(data.get('name')), category: String(data.get('category')), city: String(data.get('city')), wifi: data.get('wifi') === 'on', outlets: data.get('outlets') === 'on', seating: data.get('seating') === 'on', food: data.get('food') === 'on', lat: 52.52, lng: 13.405, created_by: user.data.user?.id }; const { data: saved, error } = await supabase.from('places').insert(payload).select().single(); if (error) { setMessage(error.message); return }; if (saved) { setPlaces((current) => [saved as Place, ...current]); setSelected(saved as Place) }; setShowReport(false) }
  async function saveSettings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase || !admin) return; const data = new FormData(event.currentTarget); const nextTitle = String(data.get('title')); await supabase.from('site_settings').upsert({ key: 'hero_title', value: nextTitle, updated_by: (await supabase.auth.getUser()).data.user?.id }); setTitle(nextTitle); setShowAdmin(false) }
  async function deletePlace(id?: string) { if (!supabase || !admin || !id) return; await supabase.from('places').delete().eq('id', id); setPlaces((current) => current.filter((place) => place.id !== id)); setSelected(null) }

  return <main className="app-shell"><header className="topbar"><a className="brand" href="#top"><img src="/free2be-logo.svg" alt="free2be" /></a><nav><a className="active" href="#places">Places entdecken</a><a href="#about">Über free2be</a></nav><div className="account-actions">{admin && <button className="quiet-button" type="button" onClick={() => setShowAdmin(true)}>Admin</button>}{email ? <button className="quiet-button" type="button" onClick={() => supabase?.auth.signOut()}>Abmelden</button> : <button className="quiet-button" type="button" onClick={() => setShowAuth(true)}>Einloggen</button>}<button className="lime-button" type="button" onClick={openReport}>+ Place melden</button></div></header><section className="welcome" id="top"><div><p className="eyebrow">FREIE ORTE · FREIE VERBINDUNG</p><h1>{title}</h1></div><p className="welcome-copy">Orte, an denen du einfach sein,<br />arbeiten und bleiben kannst.</p></section><section className="places-section" id="places"><div className="section-top"><div className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Suche nach Ort, Stadt oder Kategorie ..." /></div><div className="view-switch"><button className={view === 'map' ? 'selected' : ''} type="button" onClick={() => setView('map')}>◉ Karte</button><button className={view === 'list' ? 'selected' : ''} type="button" onClick={() => setView('list')}>☷ Liste</button></div></div><div className={view === 'map' ? 'places-layout' : 'places-layout list-only'}><div className="place-list"><div className="list-heading"><p className="eyebrow">IN DEINER NÄHE</p><strong>{visible.length} Places gefunden</strong></div>{visible.map((place) => <button className={selected?.name === place.name ? 'place-card selected' : 'place-card'} key={place.id ?? place.name} type="button" onClick={() => setSelected(place)}><span className="place-icon">{place.category === 'Café' ? '☕' : '⌂'}</span><span><strong>{place.name}</strong><small>{place.category} · {place.city}</small><i>{[place.wifi && 'WLAN', place.outlets && 'Steckdose', place.seating && 'Sitzplätze'].filter(Boolean).join(' · ')}</i></span><b>›</b></button>)}</div>{view === 'map' && <PlacesMap places={visible} onSelect={setSelected} />}</div></section><section className="bottom-note" id="about"><span className="lime-mark">✦</span><div><p className="eyebrow">EIN ORT VON MENSCHEN FÜR MENSCHEN</p><h2>Du darfst Raum<br /><em>einnehmen.</em></h2></div><p>Du kennst einen Ort, an dem sich andere<br />willkommen fühlen? Teile ihn.</p><button className="outline-button" type="button" onClick={openReport}>Place melden ↗</button></section>
+    {showAuth && <div className="modal-backdrop" onClick={() => setShowAuth(false)}><form className="modal-card" onSubmit={authSubmit} onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setShowAuth(false)}>×</button><div className="mode-tabs"><button className={authMode === 'login' ? 'selected' : ''} type="button" onClick={() => setAuthMode('login')}>Einloggen</button><button className={authMode === 'signup' ? 'selected' : ''} type="button" onClick={() => setAuthMode('signup')}>Registrieren</button></div><h2>{authMode === 'login' ? 'Willkommen zurück.' : 'Account erstellen.'}</h2><p className="modal-copy">{supabaseConfigured ? 'Sicher mit free2be verbinden.' : 'Backend noch nicht verbunden.'}</p><label>E-Mail<input name="email" required type="email" placeholder="du@beispiel.de" /></label><label>Passwort<input name="password" required minLength={8} type="password" placeholder="Mindestens 8 Zeichen" /></label>{message && <p className="form-message">{message}</p>}<button className="lime-button submit-button" type="submit">{authMode === 'login' ? 'Einloggen' : 'Registrieren'} <span>↗</span></button></form></div>}
+    {showReport && <div className="modal-backdrop" onClick={() => setShowReport(false)}><form className="modal-card report-card" onSubmit={reportSubmit} onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setShowReport(false)}>×</button><p className="eyebrow">FÜR DIE COMMUNITY</p><h2>Place melden.</h2><p className="modal-copy">Nur eingeloggte Nutzer können Places einreichen.</p><label>Name des Ortes<input name="name" required placeholder="z. B. Hotel Lobby" /></label><div className="form-grid"><label>Kategorie<select name="category"><option>Café</option><option>Hotel Lobby</option><option>Bibliothek</option><option>Sonstiger Ort</option></select></label><label>Stadt / Adresse<input name="city" required placeholder="Berlin" /></label></div><p className="field-label">Was gibt es vor Ort?</p><div className="checks"><label><input name="wifi" type="checkbox" defaultChecked /> Kostenloses WLAN</label><label><input name="outlets" type="checkbox" defaultChecked /> Steckdosen</label><label><input name="seating" type="checkbox" defaultChecked /> Sitzplätze</label><label><input name="food" type="checkbox" /> Café / Bistro</label></div><button className="lime-button submit-button" type="submit">Place einreichen <span>↗</span></button></form></div>}
+    {showAdmin && <div className="modal-backdrop" onClick={() => setShowAdmin(false)}><div className="modal-card admin-card" onClick={(event) => event.stopPropagation()}><button className="modal-close" type="button" onClick={() => setShowAdmin(false)}>×</button><p className="eyebrow">ADMIN BEREICH</p><h2>free2be verwalten.</h2><form onSubmit={saveSettings}><label>Hero-Titel der Website<input name="title" defaultValue={title} /></label><button className="lime-button submit-button" type="submit">Website speichern <span>↗</span></button></form><p className="field-label">Places verwalten</p><div className="admin-places">{places.map((place) => <div key={place.id ?? place.name}><span>{place.name}<small>{place.city}</small></span>{place.id && <button type="button" onClick={() => deletePlace(place.id)}>Löschen</button>}</div>)}</div></div></div>}
  </main>
}

export default App
